# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.define "scribe" do |scribe|

    scribe.vm.boot_timeout = 600

    scribe.vm.box = "ubuntu/trusty64"

    #scribe.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    #config.vm.hostname = "virtualbox"

    # network config
    scribe.vm.network :private_network, ip: "192.168.33.40"
    scribe.vm.network :forwarded_port, guest: 80, host: 8081
    scribe.vm.network :forwarded_port, id: 'ssh', guest: 22, host: 2322, auto_correct: false,  d: "ssh"

    # Sync overall cloudstart directory on host machine with "/vagrant" directory on guest machine
    scribe.vm.synced_folder "../../html", "/var/www/html", group: "vagrant", owner: "vagrant", create: true
    scribe.vm.synced_folder "../../scripts", "/opt/scripts", group: "www-data", owner: "www-data", create: true
    
    # Launch virtualbox GUI window
    scribe.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 1024
    end
  end

  # Run our ansible modules
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
    ansible.verbose = "vvv"
  end

end
